### PR TITLE
Timed mode + Last Stand map

### PR DESCRIPTION
**Pull request by Marmio64**
## About The Pull Request

Adds a 'Timed' game mode, where Heartfelt must defend something called the 'Sanctified Statue' for 10 minutes. Grenzelhoft meanwhile must destroy it. This game mode will work on any map so long as the warfarestatue object is added to it before the barriers fall.

In addition, includes a dedicated timed game mode map that is tailor built for it. It favors heartfelt more with it's multi layered defences and forces Grenzelhoft to work to get inside via building their own wall ladders or blowing holes into the wooden outer works. The map includes a decent bit of flavor and decoration as well.

Picture of z-level 1 for the 'Last Stand' map.

image

picture of z-level 2

image

third z-level isnt very interesting but here it is too

image

## Why It's Good For The Game

Timed game mode sounds very fun to me. Also, extra map variety.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
Use the SDMM screenshot feature, I beg you

**Comment by Marmio64** [comment]
> Use the SDMM screenshot feature, I beg you

I use fastdmm2, so I cant

**Comment by Marmio64** [comment]
working map rotation votes for bloodfort and last stand are in...

**Review by 77seven77seven — APPROVED** [review]
Very cool.

**Pull request merged**
